### ISSUE TITLE
Inconsistent link styles

### ISSUE THREAD

**Issue by mattsolo1** [covid19-hg/covid19hg#58]
The new homepage links and blog page links have different styles (size & color). Would be nice to make these all dark blue.

I also have a slight preference for removing the text decoration/underline from the links.

![image](https://user-images.githubusercontent.com/8867295/92945030-b7ec3f00-f422-11ea-9d69-59525e9c407e.png)

**Comment by huy-nguyen** [comment]
The home page and blog links now look the same. I've removed the underline from those links in normal view but retain them for hover state to let the user know that those texts are clickable in case that's not obvious.
