### ISSUE TITLE
Underscores inadvertently substituted for italics using admin console.

### ISSUE THREAD

**Issue by mattsolo1** [covid19-hg/covid19hg#62]
# Bug report

**What is the current behavior?**

Text containing underscores is interpreted as italic formatting -- in particular filenames on the _in silico_ page. It's possible to escape the underscores when editing a page in **raw markdown**, but as soon as someone edits the page using the **Admin UI**, the escape characters are removed and the text is displayed in italic.

**If the current behavior is a bug, please provide the steps to reproduce.**

e.g. on the [_in silico_](https://www.covid19hg.org/blog/2020-06-29-in-silico-follow-up-results/) page, COVID19HGIANAB2V2_20200629 should be COVID19_HGI_ANA_B2_V2_20200629

![image](https://user-images.githubusercontent.com/8867295/92951316-284b8e00-f42c-11ea-95d8-3a0ac77d5bff.png)

**What is the expected behavior?**

Ideally when the page is edited through the admin console, the escape characters would not be removed. Not sure if there is an easy way to fix this.

**Comment by huy-nguyen** [comment]
I did some investigation by adding escaped and unescaped underscores into various types of Markdown content in the site and found that there seems to be a difference between how underscores are handled when they appear in frontmatter fields and in the body. 

In https://github.com/covid19-hg/covid19hg/commit/5763235e29eb0f08263766d5077e9a088fd26ab5, I added test phrases to the frontmatter and body fields:

<img width="628" alt="Screen Shot 2020-09-11 at 6 35 47 PM" src="https://user-images.githubusercontent.com/7352279/92978463-ce63bc00-f45d-11ea-81d7-e0097f9bfb5d.png">

and the the rendered results look different:

<img width="667" alt="Screen Shot 2020-09-11 at 6 33 10 PM" src="https://user-images.githubusercontent.com/7352279/92978484-dcb1d800-f45d-11ea-8bc9-2b2f3fe15c5b.png">

A possible reason for the discrepancy is that the Markdown content in the Projects page's frontmatter is rendered at run time by ReactMarkdown:

 https://github.com/covid19-hg/covid19hg/blob/27e5a3e7d4a6135874fad69ff5ae737dab65d5f3/src/components/ProjectsPageContent.tsx#L25

whereas the Markdown in the body of a blog post is statically rendered into HTML by `gatsby-transformer-remark`.

I also found that when switching from "rich text" to "markdown" modes, Netlify CMS's markdown widget does not escape underscores entered in "rich text" mode even though their markdown escaping [unit test](https://github.com/netlify/netlify-cms/blob/66afd413c3d175fefbfd9a4b51d64ac64f951e65/packages/netlify-cms-widget-markdown/src/serializers/__tests__/remarkEscapeMarkdownEntities.spec.js) passes when provided with the phrase I used for testing. I suspect that the switch from "rich text" to "markdown" modes doesn't trigger escaping as it should.

**Comment by mattsolo1** [comment]
What's the status on this @huy-nguyen? I remember you tried a few things but there were some big obstacles.

**Comment by mattsolo1** [comment]
@huy-nguyen, based on your last message, the takeaway is there is no way to fix this? Should this issue be closed?

**Comment by huy-nguyen** [comment]
The takeaway is that Netlify CMS' markdown editor doesn't escape underscores properly when switching from rich text mode to markdown mode, even though their own test suites do not reveal any problem. The solution is that writers should manually escape underscores in both rich text and markdown modes. I can close the issue.
